-- Auto generated by RAPID
-- By: Martin C. Carlisle and W. Blair Watkinson II
with Mcc.Gui.Menu;
with Mcc.Gui.Widget.Button.Picture;
with Mcc.Gui.Image;
with Mcc.Gui.Widget.Button.Text;
with Mcc.Gui.Container.Window;

package main_window is
   main_Menu : aliased Mcc.Gui.Menu.Window_Menu;
   Actions_SubMenu : aliased Mcc.Gui.Menu.SubMenu;
   Action1_Choice : aliased Mcc.Gui.Menu.Choice;
   Action2_Choice : aliased Mcc.Gui.Menu.Choice;
   action1 : aliased Mcc.Gui.Widget.Button.Text.Text_Button;
   cut : aliased Mcc.Gui.Widget.Button.Picture.Picture_Button;
   cut_gif_gif_Image : aliased Mcc.Gui.Image.External_Image;

   main_window : aliased Mcc.Gui.Container.Window.Main_Window;

   procedure Generate_Window;

end main_window;
