-- Auto generated by RAPID
-- By: Martin C. Carlisle and W. Blair Watkinson II

with Subwindow_Actions;
with Subwindow_Actions;
with Subwindow_Actions;


with Mcc.Gui.Fonts;

package body dropdown_dialog_window is

   procedure Generate_Window is
   begin

      Mcc.Gui.Container.Window.Create(
         Obj    => dropdown_dialog_window,
         X      => 0,
         Y      => 0,
         Width  => 440,
         Height => 208);

      Mcc.Gui.Container.Window.Set_Title(
         Obj   => dropdown_dialog_window,
         Title => "Dropdown Properties");


      Mcc.Gui.Widget.Label.Create(
         Obj     => label1,
         Parent  => dropdown_dialog_window,
         X       => 0,
         Y       => 35,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.center,
         Text    => "Widget name");
      Mcc.Gui.Widget.Label.Set_Foreground_Color(
         Obj       => label1,
         New_Color => Mcc.Gui.Colors.Named_Color(
            Mcc.Gui.Colors.black));
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry1,
         Parent => dropdown_dialog_window,
         X      => 110,
         Y      => 35,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label2,
         Parent  => dropdown_dialog_window,
         X       => 0,
         Y       => 65,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.center,
         Text    => "X");
      Mcc.Gui.Widget.Label.Set_Foreground_Color(
         Obj       => label2,
         New_Color => Mcc.Gui.Colors.Named_Color(
            Mcc.Gui.Colors.black));
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry2,
         Parent => dropdown_dialog_window,
         X      => 110,
         Y      => 65,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label3,
         Parent  => dropdown_dialog_window,
         X       => 0,
         Y       => 95,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.center,
         Text    => "Y");
      Mcc.Gui.Widget.Label.Set_Foreground_Color(
         Obj       => label3,
         New_Color => Mcc.Gui.Colors.Named_Color(
            Mcc.Gui.Colors.black));
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry3,
         Parent => dropdown_dialog_window,
         X      => 110,
         Y      => 95,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label4,
         Parent  => dropdown_dialog_window,
         X       => 0,
         Y       => 125,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.center,
         Text    => "Width");
      Mcc.Gui.Widget.Label.Set_Foreground_Color(
         Obj       => label4,
         New_Color => Mcc.Gui.Colors.Named_Color(
            Mcc.Gui.Colors.black));
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry4,
         Parent => dropdown_dialog_window,
         X      => 110,
         Y      => 125,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label5,
         Parent  => dropdown_dialog_window,
         X       => 0,
         Y       => 155,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.center,
         Text    => "Height");
      Mcc.Gui.Widget.Label.Set_Foreground_Color(
         Obj       => label5,
         New_Color => Mcc.Gui.Colors.Named_Color(
            Mcc.Gui.Colors.black));
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry5,
         Parent => dropdown_dialog_window,
         X      => 110,
         Y      => 155,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label6,
         Parent  => dropdown_dialog_window,
         X       => 220,
         Y       => 35,
         Width   => 95,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.center,
         Text    => "Foreground Color");
      Mcc.Gui.Widget.Label.Set_Foreground_Color(
         Obj       => label6,
         New_Color => Mcc.Gui.Colors.Named_Color(
            Mcc.Gui.Colors.black));
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry6,
         Parent => dropdown_dialog_window,
         X      => 318,
         Y      => 36,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label7,
         Parent  => dropdown_dialog_window,
         X       => 220,
         Y       => 65,
         Width   => 95,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.center,
         Text    => "Background Color");
      Mcc.Gui.Widget.Label.Set_Foreground_Color(
         Obj       => label7,
         New_Color => Mcc.Gui.Colors.Named_Color(
            Mcc.Gui.Colors.black));
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry7,
         Parent => dropdown_dialog_window,
         X      => 318,
         Y      => 65,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label8,
         Parent  => dropdown_dialog_window,
         X       => 220,
         Y       => 95,
         Width   => 95,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.center,
         Text    => "Number of Rows");
      Mcc.Gui.Widget.Label.Set_Foreground_Color(
         Obj       => label8,
         New_Color => Mcc.Gui.Colors.Named_Color(
            Mcc.Gui.Colors.black));
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => Row_Entry,
         Parent => dropdown_dialog_window,
         X      => 318,
         Y      => 95,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => option1,
         Parent  => dropdown_dialog_window,
         X       => 3,
         Y       => 5,
         Width   => 207,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.center,
         Text    => "General Options");
      Mcc.Gui.Widget.Label.Set_Background_Color(
         Obj       => option1,
         New_Color => Mcc.Gui.Colors.Named_Color(
            Mcc.Gui.Colors.LightBlue));
      Mcc.Gui.Widget.Label.Set_Foreground_Color(
         Obj       => option1,
         New_Color => Mcc.Gui.Colors.Named_Color(
            Mcc.Gui.Colors.black));
      Mcc.Gui.Widget.Label.Create(
         Obj     => option2,
         Parent  => dropdown_dialog_window,
         X       => 220,
         Y       => 5,
         Width   => 210,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.center,
         Text    => "Dropdown Options");
      Mcc.Gui.Widget.Label.Set_Background_Color(
         Obj       => option2,
         New_Color => Mcc.Gui.Colors.Named_Color(
            Mcc.Gui.Colors.LightBlue));
      Mcc.Gui.Widget.Label.Set_Foreground_Color(
         Obj       => option2,
         New_Color => Mcc.Gui.Colors.Named_Color(
            Mcc.Gui.Colors.black));
      Mcc.Gui.Widget.Button.Text.Create(
         Obj    => applyButton,
         Parent => dropdown_dialog_window,
         X      => 225,
         Y      => 174,
         Width  => 60,
         Height => 20,
         Text   => "Apply");
      Mcc.Gui.Widget.Button.Set_Push_Callback(
         Obj      => applyButton'access,
         Callback => Subwindow_Actions.Apply_Properties_Dialog'access);
      Mcc.Gui.Widget.Button.Text.Create(
         Obj    => okbutton,
         Parent => dropdown_dialog_window,
         X      => 295,
         Y      => 174,
         Width  => 60,
         Height => 20,
         Text   => "OK");
      Mcc.Gui.Widget.Button.Set_Push_Callback(
         Obj      => okbutton'access,
         Callback => Subwindow_Actions.Done_Properties_Dialog'access);
      Mcc.Gui.Widget.Button.Text.Create(
         Obj    => cancelButton,
         Parent => dropdown_dialog_window,
         X      => 365,
         Y      => 174,
         Width  => 60,
         Height => 20,
         Text   => "Cancel");
      Mcc.Gui.Widget.Button.Set_Push_Callback(
         Obj      => cancelButton'access,
         Callback => Subwindow_Actions.Cancel_Properties_Dialog'access);

   end Generate_Window;


end dropdown_dialog_window;
