-- Auto generated by RAPID
-- By: Martin C. Carlisle and W. Blair Watkinson II
with Mcc.Gui.Widget.Button.Text;
with Mcc.Gui.Widget.Text_Entry;
with Mcc.Gui.Widget.Label;
with Mcc.Gui.Colors;
with Mcc.Gui.Container.Window;

package dropdown_dialog_window is
   label1 : aliased Mcc.Gui.Widget.Label.Label;
   entry1 : aliased Mcc.Gui.Widget.Text_Entry.Text_Entry;
   label2 : aliased Mcc.Gui.Widget.Label.Label;
   entry2 : aliased Mcc.Gui.Widget.Text_Entry.Text_Entry;
   label3 : aliased Mcc.Gui.Widget.Label.Label;
   entry3 : aliased Mcc.Gui.Widget.Text_Entry.Text_Entry;
   label4 : aliased Mcc.Gui.Widget.Label.Label;
   entry4 : aliased Mcc.Gui.Widget.Text_Entry.Text_Entry;
   label5 : aliased Mcc.Gui.Widget.Label.Label;
   entry5 : aliased Mcc.Gui.Widget.Text_Entry.Text_Entry;
   label6 : aliased Mcc.Gui.Widget.Label.Label;
   entry6 : aliased Mcc.Gui.Widget.Text_Entry.Text_Entry;
   label7 : aliased Mcc.Gui.Widget.Label.Label;
   entry7 : aliased Mcc.Gui.Widget.Text_Entry.Text_Entry;
   label8 : aliased Mcc.Gui.Widget.Label.Label;
   Row_Entry : aliased Mcc.Gui.Widget.Text_Entry.Text_Entry;
   option1 : aliased Mcc.Gui.Widget.Label.Label;
   option2 : aliased Mcc.Gui.Widget.Label.Label;
   applyButton : aliased Mcc.Gui.Widget.Button.Text.Text_Button;
   okbutton : aliased Mcc.Gui.Widget.Button.Text.Text_Button;
   cancelButton : aliased Mcc.Gui.Widget.Button.Text.Text_Button;

   dropdown_dialog_window : aliased Mcc.Gui.Container.Window.SubWindow;

   procedure Generate_Window;

end dropdown_dialog_window;
