-- Auto generated by RAPID
-- By: Martin C. Carlisle and W. Blair Watkinson II
with Mcc.Gui.Widget.Label;
with Mcc.Gui.Colors;
with Mcc.Gui.Widget.Listbox;
with Mcc.Gui.Colors;
with Mcc.Gui.Widget.Button.Text;
with Mcc.Gui.Container.Window;

package font_selection_dialog_window is
   defaultButton : aliased Mcc.Gui.Widget.Button.Text.Text_Button;
   okbutton : aliased Mcc.Gui.Widget.Button.Text.Text_Button;
   cancelButton : aliased Mcc.Gui.Widget.Button.Text.Text_Button;
   family_box : aliased Mcc.Gui.Widget.Listbox.Listbox;
   style_box : aliased Mcc.Gui.Widget.Listbox.Listbox;
   size_box : aliased Mcc.Gui.Widget.Listbox.Listbox;
   family_label : aliased Mcc.Gui.Widget.Label.Label;
   style_label : aliased Mcc.Gui.Widget.Label.Label;
   size_label : aliased Mcc.Gui.Widget.Label.Label;

   font_selection_dialog_window : aliased Mcc.Gui.Container.Window.SubWindow;

   procedure Generate_Window;

end font_selection_dialog_window;
