-- Auto generated by RAPID
-- By: Martin C. Carlisle and W. Blair Watkinson II
with Mcc.Gui.Menu;
with Mcc.Gui.Widget.Label;
with Mcc.Gui.Colors;
with Mcc.Gui.Widget.Button.Picture;
with Mcc.Gui.Image;
with Mcc.Gui.Container.Window;

package main_window is
   main_Menu : aliased Mcc.Gui.Menu.Window_Menu;
   File_SubMenu : aliased Mcc.Gui.Menu.SubMenu;
   New_Choice : aliased Mcc.Gui.Menu.Choice;
   Open_Choice : aliased Mcc.Gui.Menu.Choice;
   Close_Choice : aliased Mcc.Gui.Menu.Choice;
   Save_Choice : aliased Mcc.Gui.Menu.Choice;
   Save_As_Choice : aliased Mcc.Gui.Menu.Choice;
   Exit_Choice : aliased Mcc.Gui.Menu.Choice;
   Edit_SubMenu : aliased Mcc.Gui.Menu.SubMenu;
   Modify_Window_Choice : aliased Mcc.Gui.Menu.Choice;
   Delete_Choice : aliased Mcc.Gui.Menu.Choice;
   Duplicate_Choice : aliased Mcc.Gui.Menu.Choice;
   Tools_SubMenu : aliased Mcc.Gui.Menu.SubMenu;
   Compile_Choice : aliased Mcc.Gui.Menu.Choice;
   Help_SubMenu : aliased Mcc.Gui.Menu.SubMenu;
   About_Choice : aliased Mcc.Gui.Menu.Choice;
   newButton : aliased Mcc.Gui.Widget.Button.Picture.Picture_Button;
   new_gif_gif_Image : aliased Mcc.Gui.Image.External_Image;
   openButton : aliased Mcc.Gui.Widget.Button.Picture.Picture_Button;
   open_gif_gif_Image : aliased Mcc.Gui.Image.External_Image;
   saveButton : aliased Mcc.Gui.Widget.Button.Picture.Picture_Button;
   save_gif_gif_Image : aliased Mcc.Gui.Image.External_Image;
   menubutton : aliased Mcc.Gui.Widget.Button.Picture.Picture_Button;
   menu_gif_gif_Image : aliased Mcc.Gui.Image.External_Image;
   cutButton : aliased Mcc.Gui.Widget.Button.Picture.Picture_Button;
   cut_gif_gif_Image : aliased Mcc.Gui.Image.External_Image;
   duplicatebutton : aliased Mcc.Gui.Widget.Button.Picture.Picture_Button;
   copy_gif_gif_Image : aliased Mcc.Gui.Image.External_Image;
   compileButton : aliased Mcc.Gui.Widget.Button.Picture.Picture_Button;
   compile_gif_gif_Image : aliased Mcc.Gui.Image.External_Image;
   labelButton : aliased Mcc.Gui.Widget.Button.Picture.Picture_Button;
   label_gif_gif_Image : aliased Mcc.Gui.Image.External_Image;
   textBButton : aliased Mcc.Gui.Widget.Button.Picture.Picture_Button;
   text_button_gif_gif_Image : aliased Mcc.Gui.Image.External_Image;
   pictureBButton : aliased Mcc.Gui.Widget.Button.Picture.Picture_Button;
   picture_button_gif_gif_Image : aliased Mcc.Gui.Image.External_Image;
   textEntryButton : aliased Mcc.Gui.Widget.Button.Picture.Picture_Button;
   text_entry_gif_gif_Image : aliased Mcc.Gui.Image.External_Image;
   check_button : aliased Mcc.Gui.Widget.Button.Picture.Picture_Button;
   check_gif_gif_Image : aliased Mcc.Gui.Image.External_Image;
   radio_button : aliased Mcc.Gui.Widget.Button.Picture.Picture_Button;
   radio_button_gif_gif_Image : aliased Mcc.Gui.Image.External_Image;
   picture_select : aliased Mcc.Gui.Widget.Button.Picture.Picture_Button;
   picture_gif_gif_Image : aliased Mcc.Gui.Image.External_Image;
   listboxButton : aliased Mcc.Gui.Widget.Button.Picture.Picture_Button;
   listbox_gif_gif_Image : aliased Mcc.Gui.Image.External_Image;
   scaleButton : aliased Mcc.Gui.Widget.Button.Picture.Picture_Button;
   scale_button_gif_gif_Image : aliased Mcc.Gui.Image.External_Image;
   progressbutton : aliased Mcc.Gui.Widget.Button.Picture.Picture_Button;
   progress_button_gif_gif_Image : aliased Mcc.Gui.Image.External_Image;
   dropdownbutton : aliased Mcc.Gui.Widget.Button.Picture.Picture_Button;
   dropdown_button_gif_gif_Image : aliased Mcc.Gui.Image.External_Image;
   name : aliased Mcc.Gui.Widget.Label.Label;

   main_window : aliased Mcc.Gui.Container.Window.Main_Window;

   procedure Generate_Window;

end main_window;
