-- Auto generated by RAPID
-- By: Martin C. Carlisle and W. Blair Watkinson II

with Menu_Edit;
with Menu_Edit;


package body menuitem_dialog_window is

   procedure Generate_Window is
   begin

      Mcc.Gui.Container.Window.Create(
         Obj    => menuitem_dialog_window,
         X      => 0,
         Y      => 0,
         Width  => 230,
         Height => 157);

      Mcc.Gui.Container.Window.Set_Title(
         Obj   => menuitem_dialog_window,
         Title => "Menu Item Properties");


      Mcc.Gui.Widget.Label.Create(
         Obj     => label1,
         Parent  => menuitem_dialog_window,
         X       => 0,
         Y       => 5,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "Item name");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry1,
         Parent => menuitem_dialog_window,
         X      => 110,
         Y      => 5,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label2,
         Parent  => menuitem_dialog_window,
         X       => 0,
         Y       => 35,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "Underline position");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry2,
         Parent => menuitem_dialog_window,
         X      => 110,
         Y      => 35,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label3,
         Parent  => menuitem_dialog_window,
         X       => 0,
         Y       => 65,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "Action");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry3,
         Parent => menuitem_dialog_window,
         X      => 110,
         Y      => 65,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label4,
         Parent  => menuitem_dialog_window,
         X       => 0,
         Y       => 95,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "Accelerator");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry4,
         Parent => menuitem_dialog_window,
         X      => 110,
         Y      => 95,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Button.Text.Create(
         Obj    => okbutton,
         Parent => menuitem_dialog_window,
         X      => 33,
         Y      => 125,
         Width  => 60,
         Height => 20,
         Text   => "OK");
      Mcc.Gui.Widget.Button.Set_Push_Callback(
         Obj      => okbutton'access,
         Callback => Menu_Edit.Done_Insert_Dialog'access);
      Mcc.Gui.Widget.Button.Text.Create(
         Obj    => cancelbutton,
         Parent => menuitem_dialog_window,
         X      => 125,
         Y      => 125,
         Width  => 60,
         Height => 20,
         Text   => "Cancel");
      Mcc.Gui.Widget.Button.Set_Push_Callback(
         Obj      => cancelbutton'access,
         Callback => Menu_Edit.Cancel_Insert_Dialog'access);

   end Generate_Window;


end menuitem_dialog_window;
