-- Auto generated by RAPID
-- By: Martin C. Carlisle and W. Blair Watkinson II

with Menu_Edit;
with Menu_Edit;
with Menu_Edit;
with Menu_Edit;
with Menu_Edit;
with Menu_Edit;


with Mcc.Gui.Fonts;

package body menuedit_window is

   procedure Generate_Window is
   begin

      Mcc.Gui.Container.Window.Create(
         Obj    => menuedit_window,
         X      => 0,
         Y      => 0,
         Width  => 392,
         Height => 336);

      Mcc.Gui.Container.Window.Set_Title(
         Obj   => menuedit_window,
         Title => "Menu Editor");


      Mcc.Gui.Widget.ListBox.Create(
         Obj                  => menu_display,
         Parent               => menuedit_window,
         X                    => 2,
         Y                    => 2,
         Width                => 273,
         Height               => 326,
         Horizontal_Scrollbar =>FALSE,
         Vertical_Scrollbar   =>TRUE);
      Mcc.Gui.Widget.Listbox.Set_Background_Color(
         Obj       => menu_display,
         New_Color => Mcc.Gui.Colors.Named_Color(
            Mcc.Gui.Colors.white));
      Mcc.Gui.Widget.Listbox.Set_Foreground_Color(
         Obj       => menu_display,
         New_Color => Mcc.Gui.Colors.Named_Color(
            Mcc.Gui.Colors.black));
      Mcc.Gui.Widget.Button.Text.Create(
         Obj    => insert_menu,
         Parent => menuedit_window,
         X      => 300,
         Y      => 10,
         Width  => 71,
         Height => 25,
         Text   => "Insert Menu");
      Mcc.Gui.Widget.Button.Set_Push_Callback(
         Obj      => insert_menu'access,
         Callback => Menu_Edit.Insert_Menu'access);
      Mcc.Gui.Widget.Button.Text.Create(
         Obj    => insert_choice,
         Parent => menuedit_window,
         X      => 300,
         Y      => 50,
         Width  => 71,
         Height => 25,
         Text   => "Insert Choice");
      Mcc.Gui.Widget.Button.Set_Push_Callback(
         Obj      => insert_choice'access,
         Callback => Menu_Edit.Insert_Choice'access);
      Mcc.Gui.Widget.Button.Text.Create(
         Obj    => Insert_Separator,
         Parent => menuedit_window,
         X      => 300,
         Y      => 90,
         Width  => 71,
         Height => 25,
         Text   => "Separator");
      Mcc.Gui.Widget.Button.Set_Push_Callback(
         Obj      => Insert_Separator'access,
         Callback => Menu_Edit.Insert_Separator'access);
      Mcc.Gui.Widget.Button.Text.Create(
         Obj    => delete,
         Parent => menuedit_window,
         X      => 300,
         Y      => 130,
         Width  => 71,
         Height => 25,
         Text   => "Delete");
      Mcc.Gui.Widget.Button.Set_Push_Callback(
         Obj      => delete'access,
         Callback => Menu_Edit.Delete'access);
      Mcc.Gui.Widget.Button.Text.Create(
         Obj    => edit,
         Parent => menuedit_window,
         X      => 300,
         Y      => 170,
         Width  => 71,
         Height => 25,
         Text   => "Edit");
      Mcc.Gui.Widget.Button.Set_Push_Callback(
         Obj      => edit'access,
         Callback => Menu_Edit.Edit_Item'access);
      Mcc.Gui.Widget.Button.Text.Create(
         Obj    => done,
         Parent => menuedit_window,
         X      => 300,
         Y      => 210,
         Width  => 71,
         Height => 25,
         Text   => "Done");
      Mcc.Gui.Widget.Button.Set_Push_Callback(
         Obj      => done'access,
         Callback => Menu_Edit.Done_Edit'access);
      Mcc.Gui.Widget.Label.Create(
         Obj     => item_insert,
         Parent  => menuedit_window,
         X       => 283,
         Y       => 252,
         Width   => 101,
         Height  => 18,
         Justify => Mcc.Gui.Widget.Label.center,
         Text    => "For menus:");
      Mcc.Gui.Widget.Label.Set_Foreground_Color(
         Obj       => item_insert,
         New_Color => Mcc.Gui.Colors.Named_Color(
            Mcc.Gui.Colors.black));
      Mcc.Gui.Widget.Button.Radio.Create(
         Obj    => inside,
         Parent => menuedit_window,
         X      => 284,
         Y      => 277,
         Width  => 99,
         Height => 14,
         Text   => "Insert inside");
      Mcc.Gui.Widget.Button.Radio.Add_To_Group(
         Group    => insert_group,
         Button   => inside'access);
      Mcc.Gui.Widget.Button.Radio.Create(
         Obj    => after,
         Parent => menuedit_window,
         X      => 284,
         Y      => 293,
         Width  => 90,
         Height => 22,
         Text   => "Insert after");
      Mcc.Gui.Widget.Button.Radio.Add_To_Group(
         Group    => insert_group,
         Button   => after'access);

   end Generate_Window;


end menuedit_window;
