-- Auto generated by RAPID
-- By: Martin C. Carlisle and W. Blair Watkinson II

with File_Menu;
with File_Menu;
with File_Menu;
with File_Menu;
with File_Menu;


package body new_dialog_Window is

   procedure Generate_Window is
   begin

      Mcc.Gui.Container.Window.Create(
         Obj    => new_dialog_Window,
         X      => 0,
         Y      => 0,
         Width  => 230,
         Height => 165);

      Mcc.Gui.Container.Window.Set_Title(
         Obj   => new_dialog_Window,
         Title => "New Window Properties");


      Mcc.Gui.Widget.Label.Create(
         Obj     => label1,
         Parent  => new_dialog_Window,
         X       => 0,
         Y       => 5,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "Window name");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry1,
         Parent => new_dialog_Window,
         X      => 110,
         Y      => 5,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => title_label,
         Parent  => new_dialog_Window,
         X       => 0,
         Y       => 35,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "Title");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry4,
         Parent => new_dialog_Window,
         X      => 110,
         Y      => 35,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label2,
         Parent  => new_dialog_Window,
         X       => 0,
         Y       => 65,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "Width");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry2,
         Parent => new_dialog_Window,
         X      => 110,
         Y      => 65,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label3,
         Parent  => new_dialog_Window,
         X       => 0,
         Y       => 95,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "Height");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry3,
         Parent => new_dialog_Window,
         X      => 110,
         Y      => 95,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Button.Text.Create(
         Obj    => okbutton,
         Parent => new_dialog_Window,
         X      => 85,
         Y      => 125,
         Width  => 60,
         Height => 20,
         Text   => "OK");
      Mcc.Gui.Widget.Button.Set_Push_Callback(
         Obj      => okbutton'access,
         Callback => File_Menu.New_Done'access);

   end Generate_Window;


end new_dialog_Window;
