-- Auto generated by RAPID
-- By: Martin C. Carlisle and W. Blair Watkinson II

with Subwindow_Actions;
with Subwindow_Actions;
with Subwindow_Actions;
with Subwindow_Actions;
with Subwindow_Actions;
with Subwindow_Actions;
with Subwindow_Actions;
with Subwindow_Actions;
with Subwindow_Actions;


package body picture_dialog_Window is

   procedure Generate_Window is
   begin

      Mcc.Gui.Container.Window.Create(
         Obj    => picture_dialog_Window,
         X      => 0,
         Y      => 0,
         Width  => 230,
         Height => 217);

      Mcc.Gui.Container.Window.Set_Title(
         Obj   => picture_dialog_Window,
         Title => "Picture Properties");


      Mcc.Gui.Widget.Label.Create(
         Obj     => label1,
         Parent  => picture_dialog_Window,
         X       => 0,
         Y       => 5,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "Widget name");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry1,
         Parent => picture_dialog_Window,
         X      => 110,
         Y      => 5,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label2,
         Parent  => picture_dialog_Window,
         X       => 0,
         Y       => 35,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "X");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry2,
         Parent => picture_dialog_Window,
         X      => 110,
         Y      => 35,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label3,
         Parent  => picture_dialog_Window,
         X       => 0,
         Y       => 65,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "Y");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry3,
         Parent => picture_dialog_Window,
         X      => 110,
         Y      => 65,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label4,
         Parent  => picture_dialog_Window,
         X       => 0,
         Y       => 95,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "Width");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry4,
         Parent => picture_dialog_Window,
         X      => 110,
         Y      => 95,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label5,
         Parent  => picture_dialog_Window,
         X       => 0,
         Y       => 125,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "Height");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry5,
         Parent => picture_dialog_Window,
         X      => 110,
         Y      => 125,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label6,
         Parent  => picture_dialog_Window,
         X       => 0,
         Y       => 155,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "Picture");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry6,
         Parent => picture_dialog_Window,
         X      => 110,
         Y      => 155,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Button.Text.Create(
         Obj    => applyButton,
         Parent => picture_dialog_Window,
         X      => 20,
         Y      => 185,
         Width  => 60,
         Height => 20,
         Text   => "Apply");
      Mcc.Gui.Widget.Button.Set_Push_Callback(
         Obj      => applyButton'access,
         Callback => Subwindow_Actions.Apply_Properties_Dialog'access);
      Mcc.Gui.Widget.Button.Text.Create(
         Obj    => okbutton,
         Parent => picture_dialog_Window,
         X      => 90,
         Y      => 185,
         Width  => 60,
         Height => 20,
         Text   => "OK");
      Mcc.Gui.Widget.Button.Set_Push_Callback(
         Obj      => okbutton'access,
         Callback => Subwindow_Actions.Done_Properties_Dialog'access);
      Mcc.Gui.Widget.Button.Text.Create(
         Obj    => cancelButton,
         Parent => picture_dialog_Window,
         X      => 160,
         Y      => 185,
         Width  => 60,
         Height => 20,
         Text   => "Cancel");
      Mcc.Gui.Widget.Button.Set_Push_Callback(
         Obj      => cancelButton'access,
         Callback => Subwindow_Actions.Cancel_Properties_Dialog'access);

   end Generate_Window;


end picture_dialog_Window;
