-- Auto generated by RAPID
-- By: Martin C. Carlisle and W. Blair Watkinson II
with Mcc.Gui.Widget.Button.Text;
with Mcc.Gui.Widget.Button.Radio;
with Mcc.Gui.Widget.Text_Entry;
with Mcc.Gui.Widget.Label;
with Mcc.Gui.Colors;
with Mcc.Gui.Container.Window;

package scale_dialog_Window is
   label1 : aliased Mcc.Gui.Widget.Label.Label;
   entry1 : aliased Mcc.Gui.Widget.Text_Entry.Text_Entry;
   label2 : aliased Mcc.Gui.Widget.Label.Label;
   entry2 : aliased Mcc.Gui.Widget.Text_Entry.Text_Entry;
   label3 : aliased Mcc.Gui.Widget.Label.Label;
   entry3 : aliased Mcc.Gui.Widget.Text_Entry.Text_Entry;
   label4 : aliased Mcc.Gui.Widget.Label.Label;
   entry4 : aliased Mcc.Gui.Widget.Text_Entry.Text_Entry;
   label5 : aliased Mcc.Gui.Widget.Label.Label;
   entry5 : aliased Mcc.Gui.Widget.Text_Entry.Text_Entry;
   label6 : aliased Mcc.Gui.Widget.Label.Label;
   entry6 : aliased Mcc.Gui.Widget.Text_Entry.Text_Entry;
   label7 : aliased Mcc.Gui.Widget.Label.Label;
   entry7 : aliased Mcc.Gui.Widget.Text_Entry.Text_Entry;
   label8 : aliased Mcc.Gui.Widget.Label.Label;
   entry8 : aliased Mcc.Gui.Widget.Text_Entry.Text_Entry;
   label9 : aliased Mcc.Gui.Widget.Label.Label;
   entry9 : aliased Mcc.Gui.Widget.Text_Entry.Text_Entry;
   horizontal : aliased Mcc.Gui.Widget.Button.Radio.Radio_Button;
   vertical : aliased Mcc.Gui.Widget.Button.Radio.Radio_Button;
   label13 : aliased Mcc.Gui.Widget.Label.Label;
   applyButton : aliased Mcc.Gui.Widget.Button.Text.Text_Button;
   okbutton : aliased Mcc.Gui.Widget.Button.Text.Text_Button;
   cancelButton : aliased Mcc.Gui.Widget.Button.Text.Text_Button;
   Orientation : aliased Mcc.Gui.Widget.Button.Radio.Radio_Group;

   scale_dialog_Window : aliased Mcc.Gui.Container.Window.SubWindow;

   procedure Generate_Window;

end scale_dialog_Window;