-- Auto generated by RAPID
-- By: Martin C. Carlisle and W. Blair Watkinson II

with Subwindow_Actions;
with Subwindow_Actions;
with Subwindow_Actions;
with Subwindow_Actions;
with Subwindow_Actions;
with Subwindow_Actions;
with Subwindow_Actions;
with Subwindow_Actions;
with Subwindow_Actions;
with Subwindow_Actions;
with Subwindow_Actions;
with Subwindow_Actions;


package body scale_dialog_Window is

   procedure Generate_Window is
   begin

      Mcc.Gui.Container.Window.Create(
         Obj    => scale_dialog_Window,
         X      => 0,
         Y      => 0,
         Width  => 438,
         Height => 220);

      Mcc.Gui.Container.Window.Set_Title(
         Obj   => scale_dialog_Window,
         Title => "scale_dialog");


      Mcc.Gui.Widget.Label.Create(
         Obj     => label1,
         Parent  => scale_dialog_Window,
         X       => 0,
         Y       => 5,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "Widget name");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry1,
         Parent => scale_dialog_Window,
         X      => 110,
         Y      => 5,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label2,
         Parent  => scale_dialog_Window,
         X       => 0,
         Y       => 35,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "X");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry2,
         Parent => scale_dialog_Window,
         X      => 110,
         Y      => 35,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label3,
         Parent  => scale_dialog_Window,
         X       => 0,
         Y       => 65,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "Y");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry3,
         Parent => scale_dialog_Window,
         X      => 110,
         Y      => 65,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label4,
         Parent  => scale_dialog_Window,
         X       => 0,
         Y       => 95,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "Width");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry4,
         Parent => scale_dialog_Window,
         X      => 110,
         Y      => 95,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label5,
         Parent  => scale_dialog_Window,
         X       => 0,
         Y       => 125,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "Height");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry5,
         Parent => scale_dialog_Window,
         X      => 110,
         Y      => 125,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label6,
         Parent  => scale_dialog_Window,
         X       => 210,
         Y       => 5,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "Min");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry6,
         Parent => scale_dialog_Window,
         X      => 320,
         Y      => 5,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label7,
         Parent  => scale_dialog_Window,
         X       => 210,
         Y       => 35,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "Max");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry7,
         Parent => scale_dialog_Window,
         X      => 320,
         Y      => 35,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label8,
         Parent  => scale_dialog_Window,
         X       => 210,
         Y       => 65,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "By");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry8,
         Parent => scale_dialog_Window,
         X      => 320,
         Y      => 65,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label9,
         Parent  => scale_dialog_Window,
         X       => 210,
         Y       => 95,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "Mark Every");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry9,
         Parent => scale_dialog_Window,
         X      => 320,
         Y      => 95,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Button.Radio.Create(
         Obj    => horizontal,
         Parent => scale_dialog_Window,
         X      => 321,
         Y      => 126,
         Width  => 100,
         Height => 20,
         Text   => "Horizontal");
      Mcc.Gui.Widget.Button.Radio.Add_To_Group(
         Group    => Orientation,
         Button   => horizontal'access);
      Mcc.Gui.Widget.Button.Radio.Create(
         Obj    => vertical,
         Parent => scale_dialog_Window,
         X      => 321,
         Y      => 149,
         Width  => 100,
         Height => 20,
         Text   => "Vertical");
      Mcc.Gui.Widget.Button.Radio.Add_To_Group(
         Group    => Orientation,
         Button   => vertical'access);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label13,
         Parent  => scale_dialog_Window,
         X       => 253,
         Y       => 135,
         Width   => 75,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.center,
         Text    => "Orientation");
      Mcc.Gui.Widget.Button.Text.Create(
         Obj    => applyButton,
         Parent => scale_dialog_Window,
         X      => 93,
         Y      => 186,
         Width  => 60,
         Height => 20,
         Text   => "Apply");
      Mcc.Gui.Widget.Button.Set_Push_Callback(
         Obj      => applyButton'access,
         Callback => Subwindow_Actions.Apply_Properties_Dialog'access);
      Mcc.Gui.Widget.Button.Text.Create(
         Obj    => okbutton,
         Parent => scale_dialog_Window,
         X      => 193,
         Y      => 186,
         Width  => 60,
         Height => 20,
         Text   => "OK");
      Mcc.Gui.Widget.Button.Set_Push_Callback(
         Obj      => okbutton'access,
         Callback => Subwindow_Actions.Done_Properties_Dialog'access);
      Mcc.Gui.Widget.Button.Text.Create(
         Obj    => cancelButton,
         Parent => scale_dialog_Window,
         X      => 293,
         Y      => 186,
         Width  => 60,
         Height => 20,
         Text   => "Cancel");
      Mcc.Gui.Widget.Button.Set_Push_Callback(
         Obj      => cancelButton'access,
         Callback => Subwindow_Actions.Cancel_Properties_Dialog'access);

   end Generate_Window;


end scale_dialog_Window;
