-- Auto generated by RAPID
-- By: Martin C. Carlisle and W. Blair Watkinson II

with Menu_Edit;
with Menu_Edit;
with Menu_Edit;
with Menu_Edit;
with Menu_Edit;


package body submenu_dialog_Window is

   procedure Generate_Window is
   begin

      Mcc.Gui.Container.Window.Create(
         Obj    => submenu_dialog_Window,
         X      => 0,
         Y      => 0,
         Width  => 230,
         Height => 122);

      Mcc.Gui.Container.Window.Set_Title(
         Obj   => submenu_dialog_Window,
         Title => "Submenu Properties");


      Mcc.Gui.Widget.Label.Create(
         Obj     => label1,
         Parent  => submenu_dialog_Window,
         X       => 0,
         Y       => 5,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "Menu name");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry1,
         Parent => submenu_dialog_Window,
         X      => 110,
         Y      => 5,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label2,
         Parent  => submenu_dialog_Window,
         X       => 0,
         Y       => 35,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "Underline position");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry2,
         Parent => submenu_dialog_Window,
         X      => 110,
         Y      => 35,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label3,
         Parent  => submenu_dialog_Window,
         X       => 0,
         Y       => 65,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "Action");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry3,
         Parent => submenu_dialog_Window,
         X      => 110,
         Y      => 65,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Button.Text.Create(
         Obj    => okbutton,
         Parent => submenu_dialog_Window,
         X      => 33,
         Y      => 95,
         Width  => 60,
         Height => 20,
         Text   => "OK");
      Mcc.Gui.Widget.Button.Set_Push_Callback(
         Obj      => okbutton'access,
         Callback => Menu_Edit.Done_Insert_Dialog'access);
      Mcc.Gui.Widget.Button.Text.Create(
         Obj    => cancelbutton,
         Parent => submenu_dialog_Window,
         X      => 125,
         Y      => 95,
         Width  => 60,
         Height => 20,
         Text   => "Cancel");
      Mcc.Gui.Widget.Button.Set_Push_Callback(
         Obj      => cancelbutton'access,
         Callback => Menu_Edit.Cancel_Insert_Dialog'access);

   end Generate_Window;


end submenu_dialog_Window;
