-- Auto generated by RAPID
-- By: Martin C. Carlisle and W. Blair Watkinson II
with Mcc.Gui.Widget.Button.Text;
with Mcc.Gui.Widget.Text_Entry;
with Mcc.Gui.Widget.Label;
with Mcc.Gui.Container.Window;

package submenu_dialog_Window is
   label1 : aliased Mcc.Gui.Widget.Label.Label;
   entry1 : aliased Mcc.Gui.Widget.Text_Entry.Text_Entry;
   label2 : aliased Mcc.Gui.Widget.Label.Label;
   entry2 : aliased Mcc.Gui.Widget.Text_Entry.Text_Entry;
   label3 : aliased Mcc.Gui.Widget.Label.Label;
   entry3 : aliased Mcc.Gui.Widget.Text_Entry.Text_Entry;
   okbutton : aliased Mcc.Gui.Widget.Button.Text.Text_Button;
   cancelbutton : aliased Mcc.Gui.Widget.Button.Text.Text_Button;

   submenu_dialog_Window : aliased Mcc.Gui.Container.Window.SubWindow;

   procedure Generate_Window;

end submenu_dialog_Window;
