-- Auto generated by RAPID
-- By: Martin C. Carlisle and W. Blair Watkinson II

with Subwindow_Actions;
with Subwindow_Actions;
with Subwindow_Actions;
with Subwindow_Actions;


with Mcc.Gui.Fonts;

package body textbutton_dialog_window is

   procedure Generate_Window is
   begin

      Mcc.Gui.Container.Window.Create(
         Obj    => textbutton_dialog_window,
         X      => 0,
         Y      => 0,
         Width  => 230,
         Height => 293);

      Mcc.Gui.Container.Window.Set_Title(
         Obj   => textbutton_dialog_window,
         Title => "Textbutton Properties");


      Mcc.Gui.Widget.Label.Create(
         Obj     => label1,
         Parent  => textbutton_dialog_window,
         X       => 0,
         Y       => 5,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "Widget name");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry1,
         Parent => textbutton_dialog_window,
         X      => 110,
         Y      => 5,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label2,
         Parent  => textbutton_dialog_window,
         X       => 0,
         Y       => 35,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "X");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry2,
         Parent => textbutton_dialog_window,
         X      => 110,
         Y      => 35,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label3,
         Parent  => textbutton_dialog_window,
         X       => 0,
         Y       => 65,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "Y");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry3,
         Parent => textbutton_dialog_window,
         X      => 110,
         Y      => 65,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label4,
         Parent  => textbutton_dialog_window,
         X       => 0,
         Y       => 95,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "Width");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry4,
         Parent => textbutton_dialog_window,
         X      => 110,
         Y      => 95,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label5,
         Parent  => textbutton_dialog_window,
         X       => 0,
         Y       => 125,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "Height");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry5,
         Parent => textbutton_dialog_window,
         X      => 110,
         Y      => 125,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label6,
         Parent  => textbutton_dialog_window,
         X       => 0,
         Y       => 155,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "Action");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry6,
         Parent => textbutton_dialog_window,
         X      => 110,
         Y      => 155,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => label7,
         Parent  => textbutton_dialog_window,
         X       => 0,
         Y       => 185,
         Width   => 110,
         Height  => 20,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "Text");
      Mcc.Gui.Widget.Text_Entry.Create(
         Obj    => entry7,
         Parent => textbutton_dialog_window,
         X      => 110,
         Y      => 185,
         Width  => 100,
         Height => 20);
      Mcc.Gui.Widget.Label.Create(
         Obj     => font_label,
         Parent  => textbutton_dialog_window,
         X       => 0,
         Y       => 210,
         Width   => 110,
         Height  => 13,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "Font: ");
      Mcc.Gui.Widget.Button.Text.Create(
         Obj    => change_font,
         Parent => textbutton_dialog_window,
         X      => 122,
         Y      => 216,
         Width  => 96,
         Height => 21,
         Text   => "Change Font");
      Mcc.Gui.Widget.Button.Set_Push_Callback(
         Obj      => change_font'access,
         Callback => Subwindow_Actions.Change_Font'access);
      Mcc.Gui.Widget.Label.Create(
         Obj     => font_style,
         Parent  => textbutton_dialog_window,
         X       => 0,
         Y       => 227,
         Width   => 110,
         Height  => 15,
         Justify => Mcc.Gui.Widget.Label.left,
         Text    => "Default");
      Mcc.Gui.Widget.Button.Text.Create(
         Obj    => applyButton,
         Parent => textbutton_dialog_window,
         X      => 20,
         Y      => 254,
         Width  => 60,
         Height => 20,
         Text   => "Apply");
      Mcc.Gui.Widget.Button.Set_Push_Callback(
         Obj      => applyButton'access,
         Callback => Subwindow_Actions.Apply_Properties_Dialog'access);
      Mcc.Gui.Widget.Button.Text.Create(
         Obj    => okbutton,
         Parent => textbutton_dialog_window,
         X      => 90,
         Y      => 254,
         Width  => 60,
         Height => 20,
         Text   => "OK");
      Mcc.Gui.Widget.Button.Set_Push_Callback(
         Obj      => okbutton'access,
         Callback => Subwindow_Actions.Done_Properties_Dialog'access);
      Mcc.Gui.Widget.Button.Text.Create(
         Obj    => cancelButton,
         Parent => textbutton_dialog_window,
         X      => 160,
         Y      => 254,
         Width  => 60,
         Height => 20,
         Text   => "Cancel");
      Mcc.Gui.Widget.Button.Set_Push_Callback(
         Obj      => cancelButton'access,
         Callback => Subwindow_Actions.Cancel_Properties_Dialog'access);

   end Generate_Window;


end textbutton_dialog_window;
